name: Coverage

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install tox
      run: python -m pip install tox
    - name: Collect & Upload Coverage
      run: python -m tox -e codecov
      env:
        CODECOV_TOKEN: 08da8fb6-9366-4830-9b9e-ea9225e1a07a
